### ISSUE TITLE
Duda sobre la impresión por pantalla del fs.watch

### ISSUE THREAD

**Issue by aglezg** [ULL-ESIT-INF-DSI-2122/ull-esit-inf-dsi-21-22-prct10-async-fs-process-alu0101321219#2]
https://github.com/ULL-ESIT-INF-DSI-2122/ull-esit-inf-dsi-21-22-prct10-async-fs-process-alu0101321219/blob/25e9b2059d71941a1a1629c4ee15a671321b628c/src/ejercicio-3/noteWatcher.ts#L32-L60

Buenas, al monitorear los cambios que suceden en el directorio vigilado por el método `watcher` de `File System` me ha surgido la siguiente duda.

<img width="354" alt="image" src="https://user-images.githubusercontent.com/72389955/166002011-4b3db39c-f631-45a7-a251-c8830eaaf39c.png">

Como se puede apreciar por la imagen al eliminar una nota, el valor de el valor de la variable `eventType` del callback propio de `fs.watch` tiene el valor de _rename_ y se ejecuta el mensaje correspondiente correctamente. En cambio, al añadir una nota dicha variable toma el valor de _rename_ y posterior o a la misma vez el valor de _change_. Esto implica que salte el mensaje correspondiente a haber añadido una nota, pero también el de su modificación. ¿Sería esto correcto? ¿Hay alguna manera para solo mostrar por pantalla el primer mensaje?

Sé que en clase comentamos que al modificar ficheros era normal que el mensaje saltara 2 veces, ¿pero en el caso de que poseer `eventType` diferentes también sería normal?

@esegredo

**Comment by esegredo** [comment]
Hola, buenos días.

Si, el comportamiento es normal. Puedes dejar el código fuente con la funcionalidad que comentas.

Saludos.
