### ISSUE TITLE
Intepretación del ejercicio 4

### ISSUE THREAD

**Issue by aglezg** [ULL-ESIT-INF-DSI-2122/ull-esit-inf-dsi-21-22-prct10-async-fs-process-alu0101321219#3]
Buenas tardes, @esegredo. A la hora de realizar el ejercicio 4 de la práctica 10 implementé únicamente funciones del módulo `fs` de node.js dado que consideraba que no se debían usar comandos de linux a través del `spawn`. Sin embargo, un compañero ha contactado conmigo y me ha dicho lo contrario, que deberíamos utillizar para todas las funcionalidades `spawn`. ¿Habría algún problema?

Saludos y gracias de antemano, 
Adrián

**Comment by esegredo** [comment]
Tal y como hablamos en clase, no te preocupes.

Saludos.
